### ISSUE TITLE
New name ?

### ISSUE THREAD

**Issue by lafrech** [Jerome-github/oem_gateway#23]
There's discussion about a new name for the OEM Gateway.

I think my idea was that OEM is OpenEnergyMonitor and emon is emonCMS but this is stupid: emonTX, emonTH, etc. I should have thought twice...

From https://github.com/Jerome-github/oem_gateway/pull/21#issuecomment-39520401
- emonGateway - closest to the existing name
- emonGW - matches the TX TH CMS etc
- emonHUB - probably the simplest descriptive name

Any thought, anyone ?

**Comment by albertovm** [comment]
I have Emonhub/EmonPi and did configure OEM Gateway to send data from Arduino directly to my Raspberry USB. I had 3 issues:

1) /var/log/oemgateway is deleted all the time automaticallyy.
2) localhost url do not updates Nodes directly, but inputs.
3) node sent from Arduino is just "5", and in serial I have "5", but in URL I have 5.0 and data is sent to a wrong place.

- Does I really need to do this special configuration and execute OEM Gateway or it can be done directly from EmonPi?
- Is possible to solve the node number problem?

Thanx a lot!

**Comment by pb66** [comment]
Hi albertovm 

The place to get support for emonhub and emonpi is the [openenergymonitor forum](http://openenergymonitor.org/emon/forum). Support for usersstill using oem gateway is also provided 

Please start a thread on the forum and we will be happy to help there.

Paul

**Comment by albertovm** [comment]
Thanks a lot!
